spring:
  thymeleaf:
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot_shixun?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT
    username: root
    password: 123456

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

  mvc:
    static-path-pattern: /static/**

mybatis:
  type-aliases-package: com.example.demo.po
  mapper-locations: classpath:mapper/*Mapper.xml

